GET http://localhost:3000/customers
###

GET http://localhost:3000/customer/61f815db6573b11162c9536f

###

POST http://localhost:3000/customer
Content-Type: application/json

{
    "id": 101,
    "name": "Asad",
    "phone": "01757110297",
    "email": "test@gmil.com",
    "address": "Jhikargachha, Jessore"
}

###

PUT http://localhost:3000/customer/101
Content-Type: application/json

{
    "email": "we@gmail.com"
}

###

DELETE http://localhost:3000/customer/101