GET http://localhost:5000/customers
###

GET http://localhost:5000/customer/61f815db6573b11162c9536f

###

POST http://localhost:5000/customer
Content-Type: application/json

{
    "id": 103,
    "name": "Rohan",
    "phone": "0175711413",
    "email": "rohan@gmil.com",
    "address": "Horidrapota, Jessore"
}

###

PUT http://localhost:5000/customer/101
Content-Type: application/json

{
    "email": "we@gmail.com"
}

###

DELETE http://localhost:5000/customer/101